name: secure_archive_workspace
environment:
  sdk: ">=3.10.3 <4.0.0"
dev_dependencies:
  melos: ^7.3.0
discoverNestedWorkspaces: true
workspace: 
  - apps/secure_archive_app
  - packages/secure_archive
melos: 
  command:
    clean:
      hooks:
        pre: melos exec -c 1 -- "flutter clean"

  scripts:
    upgrade-major-tighten:
      run: |
        dart pub upgrade --major-versions --tighten
      exec:
        concurrency: 1
    validate-dependencies:
      description: Validates dependcies in the workspace
      packageFilters:
        noDependsOn: melos
      exec: |
        dart pub global run dependency_validator
    build-watch:
      description: Generate and watch files with build_runner in the workspace
      packageFilters:
        dependsOn: build_runner
      exec: |
        dart run build_runner watch --delete-conflicting-outputs
    build:
      description: Generate files with build_runner in the workspace
      packageFilters:
        dependsOn: build_runner
      run: |
        dart run build_runner build --delete-conflicting-outputs
      exec:
        failFast: true
        concurrency: 1